# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: YoungJoon H
title: Software Engineer & Researcher
email: bigjoon@sogang.ac.kr
website: bigjoon.github.io

# Social links
twitter_username: facespics
github_username:  bigjoon
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: youngjoonhwang-47aa38161
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_0.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. BigJoon 입니다.<br>
  Hi. I'm BigJoon.<br><br>
  서강대학교 낭종호 교수님 밑에서 석사과정을 진행 중 입니다.<br>
  M.S Student in Sogang University advised by Prof.Nang.<br><br>

  자신 있는 것 : <mark>TensorFlow</mark> 그리고 <mark>커피 마시기 </mark> <br>
  I am most skilled in: <mark>Tensorflow</mark> and <mark>Drinking Coffee</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Home training
   - Gaming
   - Cook
 
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
