# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: YoungJoon Hwang
title: KT Media AI Research Engineer
email: hiyoungih@naver.com
website: bigjoon.github.io

# Social links
#twitter_username: h
github_username:  bigjoon
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: -
linkedin_username: youngjoonhwang-47aa38161
# pinterest_username: jekyll
# youtube_username: channel/UCdtRAcd3L_UpV4tMXCw63NQ 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  AI Consultant Expert with a Master's degree from Sogang University, specializing in leveraging AI to solve complex business challenges. Proven experience in developing and implementing innovative AI solutions. <a href="index_ko.html">(Switch to Korean)</a>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Education

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
